## DATA ANALYSIS PROJECT

### Importing a libaries

In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings("ignore")

C:\Users\HP\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

###  Loading a data

In [2]:
Orders=pd.read_excel("Company_X_Order_Report.xlsx")
invoices=pd.read_excel("Courier_Company_Invoice.xlsx")
sku_Master=pd.read_excel("Company_X_SKU_Master.xlsx")
X_post=pd.read_excel("Company_X_Pincode_Zones.xlsx")

In [3]:
Orders

       Order ID            SKU  Order Qty
0    2001827036  8904223818706        1.0
1    2001827036  8904223819093        1.0
2    2001827036  8904223819109        1.0
3    2001827036  8904223818430        1.0
4    2001827036  8904223819277        1.0
..          ...            ...        ...
395  2001806229  8904223818942        1.0
396  2001806229  8904223818850        1.0
397  2001806226  8904223818850        2.0
398  2001806210  8904223816214        1.0
399  2001806210  8904223818874        1.0

[400 rows x 3 columns]

In [4]:
invoices

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.)
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,135.0
1,1091117222194,2001806273,1.00,121003,486886,d,Forward charges,90.2
2,1091117222931,2001806408,2.50,121003,532484,d,Forward charges,224.6
3,1091117223244,2001806458,1.00,121003,143001,b,Forward charges,61.3
4,1091117229345,2001807012,0.15,121003,515591,d,Forward charges,45.4
...,...,...,...,...,...,...,...,...
119,1091118551656,2001812941,0.73,121003,325207,d,Forward charges,90.2
120,1091117614452,2001809383,0.50,121003,303702,d,Forward and RTO charges,86.7
121,1091120922803,2001820978,0.50,121003,313301,d,Forward charges,45.4
122,1091121844806,2001811475,0.50,121003,173212,b,Forward charges,33.0
123,1091121846136,2001811305,0.50,121003,302020,d,Forward charges,45.4

## Merge function

In [5]:
# Combining a company_X_Order_Report with Courier_Company_invoice by using merge function 
# For merging a data table, i have used a "Order_ID" feature and User-defined variable "o"
O=pd.merge(Orders,invoices,on="Order ID",how="right")

# To combine a user_defined variable "o" of a new data table with Company_X_SKU_Master table by using merge fuction
#For merging a data table, i have used a "SKU" feature and User-defined variable "Ex"
Ex=pd.merge(O,sku_Master,on="SKU",how="left")

# To combine a user_defined variable "Ex" of a new data table with Company_X_Pincode_Zone table by using merge fuction
#For merging a data table, i have used a Customer_Pincode feature and User-defined variable "Ones"
Merged_dataset=pd.merge(Ex,X_post,how="inner",on="Customer Pincode")

In [6]:
O

,Order ID,SKU,Order Qty,AWB Code,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.)
0,2001806232,8904223818645,6.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0
1,2001806232,8904223819147,2.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0
2,2001806273,8904223819017,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2
3,2001806273,8904223818706,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2
4,2001806273,8904223818942,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2
...,...,...,...,...,...,...,...,...,...,...
395,2001811475,8904223819031,1.0,1091121844806,0.5,121003,173212,b,Forward charges,33.0
396,2001811305,8904223816214,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4
397,2001811305,8904223819499,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4
398,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4
399,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4

In [7]:
Ex

,Order ID,SKU,Order Qty,AWB Code,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.),Weight (g)
0,2001806232,8904223818645,6.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137
1,2001806232,8904223819147,2.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240
2,2001806273,8904223819017,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115
3,2001806273,8904223818706,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127
4,2001806273,8904223818942,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133
...,...,...,...,...,...,...,...,...,...,...,...
396,2001811475,8904223819031,1.0,1091121844806,0.5,121003,173212,b,Forward charges,33.0,112
397,2001811305,8904223816214,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,120
398,2001811305,8904223819499,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210
399,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210
400,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210

In [8]:
Merged_dataset.columns

Index(['Order ID', 'SKU', 'Order Qty', 'AWB Code', 'Charged Weight',
       'Warehouse Pincode_x', 'Customer Pincode', 'Zone_x', 'Type of Shipment',
       'Billing Amount (Rs.)', 'Weight (g)', 'Warehouse Pincode_y', 'Zone_y'],
      dtype='object')

In [9]:
# Rename the columns name as per require:
Merged_dataset.rename(columns={"Charged Weight":"Charged_Weight","Warehouse Pincode_x":"Company_Warehouse_Pincode",
                     "Customer Pincode":"Company_Customer_Pincode","Zone_x":"Company_Zone",
                     "Warehouse Pincode_y":"X_Warehouse_Pincode","Zone_y":"X_Zone","Weight (g)":"Weight(g)"},inplace=True)

In [10]:
Merged_dataset.rename(columns={"Company_Zone":"Delivery_Zone_charged_by_Courier_Company","X_Zone":"Delivery_Zone_as_per_X"},inplace=True)
Merged_dataset.rename(columns={"Charged_Weight":"Total_weight_as_per_Courier_Company_(KG)"},inplace=True)

In [11]:
Merged_dataset.columns

Index(['Order ID', 'SKU', 'Order Qty', 'AWB Code',
       'Total_weight_as_per_Courier_Company_(KG)', 'Company_Warehouse_Pincode',
       'Company_Customer_Pincode', 'Delivery_Zone_charged_by_Courier_Company',
       'Type of Shipment', 'Billing Amount (Rs.)', 'Weight(g)',
       'X_Warehouse_Pincode', 'Delivery_Zone_as_per_X'],
      dtype='object')

In [12]:
# Calculation:
   # Multiplication of Weight(g)*Order_qty, to find out the 
   #Convertion of gram to Kg of the total weight as per X company
Merged_dataset["Total_weight_as_per_X(g)"]=Merged_dataset["Order Qty"]*Merged_dataset["Weight(g)"]
Merged_dataset["Total_weight_as_per_X(Kg)"]=Merged_dataset["Total_weight_as_per_X(g)"]/1000

In [13]:
Merged_dataset

,Order ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_charged_by_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight(g),X_Warehouse_Pincode,Delivery_Zone_as_per_X,Total_weight_as_per_X(g),Total_weight_as_per_X(Kg)
0,2001806232,8904223818645,6.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,822.0,0.822
1,2001806232,8904223819147,2.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,480.0,0.480
2,2001806273,8904223819017,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,115.0,0.115
3,2001806273,8904223818706,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,127.0,0.127
4,2001806273,8904223818942,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,133.0,0.133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001811305,8904223819499,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210
563,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210
564,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210
565,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210
566,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210

## IF condition- To find out the weight_slab_as_per_X_company

In [14]:
condition=[(Merged_dataset["Total_weight_as_per_X(Kg)"]<=0.500),
          (Merged_dataset["Total_weight_as_per_X(Kg)"]>0.500)&(Merged_dataset["Total_weight_as_per_X(Kg)"]<=1),
          (Merged_dataset["Total_weight_as_per_X(Kg)"]>1)&(Merged_dataset["Total_weight_as_per_X(Kg)"]<=1.5),
          (Merged_dataset["Total_weight_as_per_X(Kg)"]>1.5)&(Merged_dataset["Total_weight_as_per_X(Kg)"]<=2),
          (Merged_dataset["Total_weight_as_per_X(Kg)"]>2)&(Merged_dataset["Total_weight_as_per_X(Kg)"]<=2.5),
          (Merged_dataset["Total_weight_as_per_X(Kg)"]>2.5)&(Merged_dataset["Total_weight_as_per_X(Kg)"]<=3),
          (Merged_dataset["Total_weight_as_per_X(Kg)"]>3)&(Merged_dataset["Total_weight_as_per_X(Kg)"]<=3.5),
          (Merged_dataset["Total_weight_as_per_X(Kg)"]>3.5)&(Merged_dataset["Total_weight_as_per_X(Kg)"]<=4)]

In [15]:
value=[0.5,1,1.5,2,2.5,3,3.5,4]

In [16]:
Merged_dataset["Weight_slab_as_per_X_(KG)"]=np.select(condition,value)

In [17]:
Merged_dataset

,Order ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_charged_by_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight(g),X_Warehouse_Pincode,Delivery_Zone_as_per_X,Total_weight_as_per_X(g),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG)
0,2001806232,8904223818645,6.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,822.0,0.822,1.0
1,2001806232,8904223819147,2.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,480.0,0.480,0.5
2,2001806273,8904223819017,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,115.0,0.115,0.5
3,2001806273,8904223818706,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,127.0,0.127,0.5
4,2001806273,8904223818942,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,133.0,0.133,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001811305,8904223819499,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5
563,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5
564,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5
565,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5
566,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5

## If condition- To find out the Weight_slab_charged_by_Courier_Company_(KG)

In [18]:
conditions=[(Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]<=0.500),
          (Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]>0.500)&(Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]<=1),
          (Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]>1)&(Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]<=1.5),
          (Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]>1.5)&(Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]<=2),
          (Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]>2)&(Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]<=2.5),
          (Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]>2.5)&(Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]<=3),
          (Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]>3)&(Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]<=3.5),
          (Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]>3.5)&(Merged_dataset["Total_weight_as_per_Courier_Company_(KG)"]<=4)]

In [19]:
value=[0.5,1,1.5,2,2.5,3,3.5,4]

In [20]:
Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]=np.select(conditions,value)

In [21]:
Merged_dataset

,Order ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_charged_by_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight(g),X_Warehouse_Pincode,Delivery_Zone_as_per_X,Total_weight_as_per_X(g),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Weight_slab_charged_by_Courier_Company_(KG)
0,2001806232,8904223818645,6.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,822.0,0.822,1.0,1.5
1,2001806232,8904223819147,2.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,480.0,0.480,0.5,1.5
2,2001806273,8904223819017,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,115.0,0.115,0.5,1.0
3,2001806273,8904223818706,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,127.0,0.127,0.5,1.0
4,2001806273,8904223818942,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,133.0,0.133,0.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001811305,8904223819499,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5
563,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5
564,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5
565,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5
566,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5

## If condition- To find out the Expected_Charge_as_per_X_(Rs.)

In [22]:
conditionss=[(Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="b")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="b")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="b")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="d")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="d")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="d")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="e")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="e")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="e")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="b")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="b")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="b")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="d")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="d")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="d")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="e")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="e")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_as_per_X"]=="e")&
             (Merged_dataset["Weight_slab_as_per_X_(KG)"]==1.5)]

In [23]:
valuess=[(Merged_dataset["Billing Amount (Rs.)"]+33),(Merged_dataset["Billing Amount (Rs.)"]+61.3),(Merged_dataset["Billing Amount (Rs.)"]+89.6),
         (Merged_dataset["Billing Amount (Rs.)"]+45.4),(Merged_dataset["Billing Amount (Rs.)"]+90.2),(Merged_dataset["Billing Amount (Rs.)"]+135),
        (Merged_dataset["Billing Amount (Rs.)"]+56.6),(Merged_dataset["Billing Amount (Rs.)"]+112.1),(Merged_dataset["Billing Amount (Rs.)"]+167.6),
        (Merged_dataset["Billing Amount (Rs.)"]+45.4),(Merged_dataset["Billing Amount (Rs.)"]+110.1),(Merged_dataset["Billing Amount (Rs.)"]+166.7),
         (Merged_dataset["Billing Amount (Rs.)"]+86.7),(Merged_dataset["Billing Amount (Rs.)"]+176.3),(Merged_dataset["Billing Amount (Rs.)"]+265.9),
         (Merged_dataset["Billing Amount (Rs.)"]+107.3),(Merged_dataset["Billing Amount (Rs.)"]+218.3),(Merged_dataset["Billing Amount (Rs.)"]+329.3)]

In [24]:
Merged_dataset["Weight_slab_as_per_X_(KG)"].value_counts()

Weight_slab_as_per_X_(KG)
0.5    554
1.0     12
1.5      1
Name: count, dtype: int64

In [25]:
Merged_dataset["Delivery_Zone_as_per_X"].value_counts()

Delivery_Zone_as_per_X
b    397
d    136
e     34
Name: count, dtype: int64

In [26]:
Merged_dataset["Type of Shipment"].value_counts()

Type of Shipment
Forward charges            517
Forward and RTO charges     50
Name: count, dtype: int64

In [27]:
Merged_dataset["Expected_Charge_as_per_X_(Rs.)"]=np.select(conditionss,valuess)

In [28]:
Merged_dataset

,Order ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_charged_by_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight(g),X_Warehouse_Pincode,Delivery_Zone_as_per_X,Total_weight_as_per_X(g),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Weight_slab_charged_by_Courier_Company_(KG),Expected_Charge_as_per_X_(Rs.)
0,2001806232,8904223818645,6.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,822.0,0.822,1.0,1.5,225.2
1,2001806232,8904223819147,2.0,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,480.0,0.480,0.5,1.5,180.4
2,2001806273,8904223819017,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,115.0,0.115,0.5,1.0,135.6
3,2001806273,8904223818706,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,127.0,0.127,0.5,1.0,135.6
4,2001806273,8904223818942,1.0,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,133.0,0.133,0.5,1.0,135.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001811305,8904223819499,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5,78.4
563,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5,78.4
564,2001811305,8904223819505,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5,78.4
565,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5,78.4
566,2001811305,8904223819512,1.0,1091121846136,0.5,121003,302020,d,Forward charges,45.4,210,121003,b,210.0,0.210,0.5,0.5,78.4

## If condition- To find out the Charges_Billed_by_Courier_Company_(Rs.)

In [29]:
con=[(Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==3),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==3),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.5),
              (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2),
              (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2.5),
              (Merged_dataset["Type of Shipment"]=="Forward charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==3),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="b")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==3),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.5), 
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2), 
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="d")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==3),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==0.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.0),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==1.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==2.5),
             (Merged_dataset["Type of Shipment"]=="Forward and RTO charges")&(Merged_dataset["Delivery_Zone_charged_by_Courier_Company"]=="e")&
             (Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"]==3)]

In [30]:
val=[(Merged_dataset["Billing Amount (Rs.)"]+33),(Merged_dataset["Billing Amount (Rs.)"]+61.3),(Merged_dataset["Billing Amount (Rs.)"]+89.6),(Merged_dataset["Billing Amount (Rs.)"]+117.9),(Merged_dataset["Billing Amount (Rs.)"]+146.2),(Merged_dataset["Billing Amount (Rs.)"]+174.5),
(Merged_dataset["Billing Amount (Rs.)"]+45.4),(Merged_dataset["Billing Amount (Rs.)"]+90.2),(Merged_dataset["Billing Amount (Rs.)"]+135),(Merged_dataset["Billing Amount (Rs.)"]+179.8),(Merged_dataset["Billing Amount (Rs.)"]+224.6),(Merged_dataset["Billing Amount (Rs.)"]+269.4),
(Merged_dataset["Billing Amount (Rs.)"]+56.6),(Merged_dataset["Billing Amount (Rs.)"]+112.1),(Merged_dataset["Billing Amount (Rs.)"]+167.6),(Merged_dataset["Billing Amount (Rs.)"]+223.1),(Merged_dataset["Billing Amount (Rs.)"]+278.6),(Merged_dataset["Billing Amount (Rs.)"]+334.1),
(Merged_dataset["Billing Amount (Rs.)"]+45.4),(Merged_dataset["Billing Amount (Rs.)"]+110.1),(Merged_dataset["Billing Amount (Rs.)"]+166.7),(Merged_dataset["Billing Amount (Rs.)"]+223.3),(Merged_dataset["Billing Amount (Rs.)"]+279.9),(Merged_dataset["Billing Amount (Rs.)"]+336.5),
(Merged_dataset["Billing Amount (Rs.)"]+86.7),(Merged_dataset["Billing Amount (Rs.)"]+176.3),(Merged_dataset["Billing Amount (Rs.)"]+265.9),(Merged_dataset["Billing Amount (Rs.)"]+355.5),(Merged_dataset["Billing Amount (Rs.)"]+445.1),(Merged_dataset["Billing Amount (Rs.)"]+534.7),
(Merged_dataset["Billing Amount (Rs.)"]+107.3),(Merged_dataset["Billing Amount (Rs.)"]+218.3),(Merged_dataset["Billing Amount (Rs.)"]+329.3),(Merged_dataset["Billing Amount (Rs.)"]+440.3),(Merged_dataset["Billing Amount (Rs.)"]+551.3),(Merged_dataset["Billing Amount (Rs.)"]+662.3)]

In [31]:
Merged_dataset["Weight_slab_charged_by_Courier_Company_(KG)"].value_counts()

Weight_slab_charged_by_Courier_Company_(KG)
1.0    261
1.5    106
0.5     78
2.0     52
2.5     41
3.0     27
0.0      2
Name: count, dtype: int64

In [32]:
Merged_dataset["Delivery_Zone_charged_by_Courier_Company"].value_counts()

Delivery_Zone_charged_by_Courier_Company
d    454
b    108
e      5
Name: count, dtype: int64

In [33]:
Merged_dataset["Charges_Billed_by_Courier_Company_(Rs.)"]=np.select(con,val)

In [34]:
Merged_dataset.columns

Index(['Order ID', 'SKU', 'Order Qty', 'AWB Code',
       'Total_weight_as_per_Courier_Company_(KG)', 'Company_Warehouse_Pincode',
       'Company_Customer_Pincode', 'Delivery_Zone_charged_by_Courier_Company',
       'Type of Shipment', 'Billing Amount (Rs.)', 'Weight(g)',
       'X_Warehouse_Pincode', 'Delivery_Zone_as_per_X',
       'Total_weight_as_per_X(g)', 'Total_weight_as_per_X(Kg)',
       'Weight_slab_as_per_X_(KG)',
       'Weight_slab_charged_by_Courier_Company_(KG)',
       'Expected_Charge_as_per_X_(Rs.)',
       'Charges_Billed_by_Courier_Company_(Rs.)'],
      dtype='object')

## Calculation of Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.)

In [35]:
Merged_dataset["Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.)"]=Merged_dataset["Expected_Charge_as_per_X_(Rs.)"]-Merged_dataset["Charges_Billed_by_Courier_Company_(Rs.)"]

In [36]:
Merged_dataset.columns

Index(['Order ID', 'SKU', 'Order Qty', 'AWB Code',
       'Total_weight_as_per_Courier_Company_(KG)', 'Company_Warehouse_Pincode',
       'Company_Customer_Pincode', 'Delivery_Zone_charged_by_Courier_Company',
       'Type of Shipment', 'Billing Amount (Rs.)', 'Weight(g)',
       'X_Warehouse_Pincode', 'Delivery_Zone_as_per_X',
       'Total_weight_as_per_X(g)', 'Total_weight_as_per_X(Kg)',
       'Weight_slab_as_per_X_(KG)',
       'Weight_slab_charged_by_Courier_Company_(KG)',
       'Expected_Charge_as_per_X_(Rs.)',
       'Charges_Billed_by_Courier_Company_(Rs.)',
       'Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.)'],
      dtype='object')

## Delete the unwanted columns as per report:

In [37]:
Report=Merged_dataset

In [38]:
Report.columns

Index(['Order ID', 'SKU', 'Order Qty', 'AWB Code',
       'Total_weight_as_per_Courier_Company_(KG)', 'Company_Warehouse_Pincode',
       'Company_Customer_Pincode', 'Delivery_Zone_charged_by_Courier_Company',
       'Type of Shipment', 'Billing Amount (Rs.)', 'Weight(g)',
       'X_Warehouse_Pincode', 'Delivery_Zone_as_per_X',
       'Total_weight_as_per_X(g)', 'Total_weight_as_per_X(Kg)',
       'Weight_slab_as_per_X_(KG)',
       'Weight_slab_charged_by_Courier_Company_(KG)',
       'Expected_Charge_as_per_X_(Rs.)',
       'Charges_Billed_by_Courier_Company_(Rs.)',
       'Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.)'],
      dtype='object')

In [39]:
dele=["SKU","Order Qty","Company_Warehouse_Pincode","Company_Customer_Pincode","Type of Shipment",
      "Billing Amount (Rs.)","Weight(g)","X_Warehouse_Pincode","Total_weight_as_per_X(g)"]

In [40]:
for i in dele:
    Report.drop([i],inplace=True,axis=1)

In [41]:
Report

,Order ID,AWB Code,Total_weight_as_per_Courier_Company_(KG),Delivery_Zone_charged_by_Courier_Company,Delivery_Zone_as_per_X,Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Weight_slab_charged_by_Courier_Company_(KG),Expected_Charge_as_per_X_(Rs.),Charges_Billed_by_Courier_Company_(Rs.),Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.)
0,2001806232,1091117222124,1.3,d,d,0.822,1.0,1.5,225.2,270.0,-44.8
1,2001806232,1091117222124,1.3,d,d,0.480,0.5,1.5,180.4,270.0,-89.6
2,2001806273,1091117222194,1.0,d,d,0.115,0.5,1.0,135.6,180.4,-44.8
3,2001806273,1091117222194,1.0,d,d,0.127,0.5,1.0,135.6,180.4,-44.8
4,2001806273,1091117222194,1.0,d,d,0.133,0.5,1.0,135.6,180.4,-44.8
...,...,...,...,...,...,...,...,...,...,...,...
562,2001811305,1091121846136,0.5,d,b,0.210,0.5,0.5,78.4,90.8,-12.4
563,2001811305,1091121846136,0.5,d,b,0.210,0.5,0.5,78.4,90.8,-12.4
564,2001811305,1091121846136,0.5,d,b,0.210,0.5,0.5,78.4,90.8,-12.4
565,2001811305,1091121846136,0.5,d,b,0.210,0.5,0.5,78.4,90.8,-12.4
566,2001811305,1091121846136,0.5,d,b,0.210,0.5,0.5,78.4,90.8,-12.4

## Arrange the features as per report submission:

In [42]:
Final_Report=Report[["Order ID","AWB Code","Total_weight_as_per_X(Kg)","Weight_slab_as_per_X_(KG)",
                     "Total_weight_as_per_Courier_Company_(KG)","Weight_slab_charged_by_Courier_Company_(KG)",
                     "Delivery_Zone_as_per_X","Delivery_Zone_charged_by_Courier_Company","Expected_Charge_as_per_X_(Rs.)",
                    "Charges_Billed_by_Courier_Company_(Rs.)","Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.)"]]

In [43]:
submission=Final_Report

In [44]:
submission

,Order ID,AWB Code,Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Total_weight_as_per_Courier_Company_(KG),Weight_slab_charged_by_Courier_Company_(KG),Delivery_Zone_as_per_X,Delivery_Zone_charged_by_Courier_Company,Expected_Charge_as_per_X_(Rs.),Charges_Billed_by_Courier_Company_(Rs.),Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.)
0,2001806232,1091117222124,0.822,1.0,1.3,1.5,d,d,225.2,270.0,-44.8
1,2001806232,1091117222124,0.480,0.5,1.3,1.5,d,d,180.4,270.0,-89.6
2,2001806273,1091117222194,0.115,0.5,1.0,1.0,d,d,135.6,180.4,-44.8
3,2001806273,1091117222194,0.127,0.5,1.0,1.0,d,d,135.6,180.4,-44.8
4,2001806273,1091117222194,0.133,0.5,1.0,1.0,d,d,135.6,180.4,-44.8
...,...,...,...,...,...,...,...,...,...,...,...
562,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4
563,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4
564,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4
565,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4
566,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4

In [45]:
# If condition- To find out the "Total orders where X has been correctly charged"
cK=[(submission["Charges_Billed_by_Courier_Company_(Rs.)"])==(submission["Expected_Charge_as_per_X_(Rs.)"])]
VO=[submission["Expected_Charge_as_per_X_(Rs.)"]]
submission["Total orders where X has been correctly charged"]=np.select(cK,VO)


# If condition- To find out the "Total Orders where X has been overchargeds"
K=[(submission["Charges_Billed_by_Courier_Company_(Rs.)"])>(submission["Expected_Charge_as_per_X_(Rs.)"])]
O=[submission["Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.)"]]
submission["Total Orders where X has been overchargeds"]=np.select(K,O)


# If condition- To find out the Total Orders where X has been undercharged"
Kw=[(submission["Charges_Billed_by_Courier_Company_(Rs.)"])<(submission["Expected_Charge_as_per_X_(Rs.)"])]
Ow=[submission["Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.)"]]
submission["Total Orders where X has been undercharged"]=np.select(Kw,Ow)

In [46]:
submission

,Order ID,AWB Code,Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Total_weight_as_per_Courier_Company_(KG),Weight_slab_charged_by_Courier_Company_(KG),Delivery_Zone_as_per_X,Delivery_Zone_charged_by_Courier_Company,Expected_Charge_as_per_X_(Rs.),Charges_Billed_by_Courier_Company_(Rs.),Difference_Between_Expected_Charges_and_Billed_Charges_(Rs.),Total orders where X has been correctly charged,Total Orders where X has been overchargeds,Total Orders where X has been undercharged
0,2001806232,1091117222124,0.822,1.0,1.3,1.5,d,d,225.2,270.0,-44.8,0.0,-44.8,0.0
1,2001806232,1091117222124,0.480,0.5,1.3,1.5,d,d,180.4,270.0,-89.6,0.0,-89.6,0.0
2,2001806273,1091117222194,0.115,0.5,1.0,1.0,d,d,135.6,180.4,-44.8,0.0,-44.8,0.0
3,2001806273,1091117222194,0.127,0.5,1.0,1.0,d,d,135.6,180.4,-44.8,0.0,-44.8,0.0
4,2001806273,1091117222194,0.133,0.5,1.0,1.0,d,d,135.6,180.4,-44.8,0.0,-44.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4,0.0,-12.4,0.0
563,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4,0.0,-12.4,0.0
564,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4,0.0,-12.4,0.0
565,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4,0.0,-12.4,0.0
566,2001811305,1091121846136,0.210,0.5,0.5,0.5,b,d,78.4,90.8,-12.4,0.0,-12.4,0.0

## Converting the python file into Excel file

In [185]:
submission.to_excel("final_report.xlsx")